name: debian-10

on:
  push:
    branches:
      - debian-10
env:
  DEBIAN_FRONTEND: noninteractive
  DOCKER_TAG: debian-10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: |
          ghcr.io/netbootxyz/mod-layers:${{ env.DOCKER_TAG }}
          ghcr.io/netbootxyz/mod-layers:${{ github.sha }}
